/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Procurement;

import Business.Enterprise.Enterprise;
import Business.ExtendedClasses.NumericVerifier;
import Business.ExtendedClasses.StringVerifier;
import Business.ExtendedClasses.WorkRequestHistory;
import Business.Organization.FinanceOrganization;
import Business.Organization.Organization;
import Business.Organization.ServicingOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.InputVerifier;
import javax.swing.JPanel;

/**
 *
 * @author Abhishek
 */
public class ProcessRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessRequestJPanel
     */
    private JPanel userProcessContainer;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private WorkRequest request;
    public ProcessRequestJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise,WorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        System.out.println(enterprise+"Cons"); 
       this.enterprise = enterprise;
        this.userAccount = account;
        this.request = request;
        addVerifiers();
    }
    
    private void addVerifiers() {
        InputVerifier stringVerifier = new StringVerifier();
        TextFieldFinMessage.setInputVerifier(stringVerifier);
        TextFieldServicingMsg.setInputVerifier(stringVerifier);
        InputVerifier integerVerifier = new NumericVerifier();
        TextFieldTotalPrice.setInputVerifier(integerVerifier);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TextFieldTotalPrice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TextFieldFinMessage = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        backJButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TextFieldServicingMsg = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 204, 153));
        setMaximumSize(new java.awt.Dimension(1000, 700));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Total Price");

        TextFieldTotalPrice.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TextFieldTotalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldTotalPriceActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Message for Finance");

        TextFieldFinMessage.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TextFieldFinMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldFinMessageActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        backJButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        backJButton2.setText("<< Back");
        backJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Message for Servicing dept");

        TextFieldServicingMsg.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TextFieldServicingMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldServicingMsgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backJButton2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextFieldFinMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(214, 214, 214)
                            .addComponent(TextFieldTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TextFieldServicingMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1)))))
                .addContainerGap(295, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextFieldTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextFieldFinMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextFieldServicingMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton2)
                    .addComponent(jButton1))
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldTotalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldTotalPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldTotalPriceActionPerformed

    private void TextFieldFinMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldFinMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldFinMessageActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String price = TextFieldTotalPrice.getText();
        String finMessage = TextFieldFinMessage.getText();
        String servicingMsg = TextFieldServicingMsg.getText();
        
        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof ServicingOrganization){
                org = organization;
                break;
            }
        }
        
        if (org!=null){
        request.setMsgforServicing(servicingMsg);
        request.setStatus("Sent To Servicing");
        request.setReceiver(null);
        request.setReceiverOrg(org);
        request.setCurrentOwner(null);
        request.setCurrentOwnerOrganzation(org);
        for(WorkRequestHistory wrh :request.getWrh().getWorkRequestHisList())
        {
            if(wrh.getReceiverOrganization().equals(organization))
            {
                wrh.setConpletedDate(new Date());
                wrh.setComment(servicingMsg);
            }
        }
        org.getWorkQueue().getWorkRequestList().add(request);
        }
        
        Organization orgFin = null;
        System.out.println(enterprise);
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof FinanceOrganization){
                orgFin = organization;
                break;
            }
        }
        
        if (orgFin!=null){
            request.setStatusforFin("Procured");
            request.setProcuredDate(new Date());
            request.setTotalPrice(Integer.parseInt(price));
            request.setMsgforFin(finMessage);
            orgFin.getWorkQueue().getWorkRequestList().add(request);
        }
        
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ProcViewRequestJpanel dwjp = (ProcViewRequestJpanel) component;
        dwjp.populateworkRequestJTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton2ActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ProcViewRequestJpanel dwjp = (ProcViewRequestJpanel) component;
        dwjp.populateworkRequestJTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButton2ActionPerformed

    private void TextFieldServicingMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldServicingMsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldServicingMsgActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldFinMessage;
    private javax.swing.JTextField TextFieldServicingMsg;
    private javax.swing.JTextField TextFieldTotalPrice;
    private javax.swing.JButton backJButton2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
