/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Department;

import Business.Enterprise.Enterprise;
import Business.ExtendedClasses.SendMail;
import Business.Organization.DepartmentOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
//import java.net.PasswordAuthentication;
import javax.mail.Session;
import javax.swing.JPanel;

import java.util.Properties;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author Abhishek
 */
public class DepartmentWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DepartmentWorkAreaJPane
     */
    
    private JPanel userProcessContainer;
    private DepartmentOrganization org;
    private Enterprise enterprise;
    private UserAccount userAccount;
    public DepartmentWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, DepartmentOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.org = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        System.out.println(userAccount);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMachineJbutton = new javax.swing.JButton();
        viewMachinesJButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 153));
        setPreferredSize(new java.awt.Dimension(1000, 700));

        addMachineJbutton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addMachineJbutton.setText("ADD MACHNES");
        addMachineJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMachineJbuttonActionPerformed(evt);
            }
        });

        viewMachinesJButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        viewMachinesJButton.setText("VIEW CURRENT REQUEST");
        viewMachinesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMachinesJButtonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("VIEW COMPLETED REQUEST");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("View Not Serviced Request");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addMachineJbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewMachinesJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(570, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(addMachineJbutton)
                .addGap(29, 29, 29)
                .addComponent(viewMachinesJButton)
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addGap(53, 53, 53)
                .addComponent(jButton3)
                .addContainerGap(540, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addMachineJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMachineJbuttonActionPerformed
        // TODO add your handling code here:
        AddMachineJPanel AddMachineJPanel = new AddMachineJPanel(userProcessContainer,org,userAccount,enterprise);
        userProcessContainer.add("manageOrganizationJPanel", AddMachineJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_addMachineJbuttonActionPerformed

    private void viewMachinesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMachinesJButtonActionPerformed
        // TODO add your handling code here:
        
        System.out.println(userAccount+"Juset send");
        ViewRequestJpanel ViewRequestJpanel = new ViewRequestJpanel(userProcessContainer,org,userAccount,enterprise);
        userProcessContainer.add("ViewRequestJpanel", ViewRequestJpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewMachinesJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DepartmentViewCompletedRequest DepartmentViewCompletedRequest = new DepartmentViewCompletedRequest(userProcessContainer,org,userAccount,enterprise);
        userProcessContainer.add("DepartmentViewCompletedRequest", DepartmentViewCompletedRequest);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        /*DepartmentViewNotServiced DepartmentViewNotServiced = new DepartmentViewNotServiced(userProcessContainer,org,userAccount,enterprise);
        userProcessContainer.add("DepartmentViewNotServiced", DepartmentViewNotServiced);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);*/
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMachineJbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton viewMachinesJButton;
    // End of variables declaration//GEN-END:variables
}
